title: CY's Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: ""
url: "" 
twitter_username: 
github_username:  


markdown: 
theme: 
gems:
 
exclude:
 

